version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: npm-install
          command: npm ci
      - run:
          name: lint
          command: npm run lint
      - run:
          name: lint
          command: npm run build

workflows:
  version: 2
  test:
    jobs:
      - test
